// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI-powered flow for extracting transaction details from raw text.
 * 
 * - extractTransactionsFromText - A function that parses text to identify and structure financial transactions.
 * - ExtractTransactionsInput - The input type for the extraction flow.
 * - ExtractTransactionsOutput - The output type for the extraction flow.
 * - Transaction - A structured representation of a single financial transaction.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const TransactionSchema = z.object({
  merchant: z.string().describe('The name of the merchant or a description of the expense, like "groceries" or "transport".'),
  amount: z.number().describe('The monetary value of the transaction.'),
  date: z.string().describe('The date of the transaction in YYYY-MM-DD format.'),
  type: z.enum(['debit', 'credit']).describe('The type of transaction (debit or credit).'),
});

export type Transaction = z.infer<typeof TransactionSchema>;

const ExtractTransactionsInputSchema = z.object({
  text: z.string().describe('A block of text, potentially containing one or more transaction descriptions, like from an SMS message or user input.'),
});

export type ExtractTransactionsInput = z.infer<typeof ExtractTransactionsInputSchema>;

const ExtractTransactionsOutputSchema = z.object({
  transactions: z.array(TransactionSchema).describe('An array of structured transaction objects found in the text.'),
});

export type ExtractTransactionsOutput = z.infer<typeof ExtractTransactionsOutputSchema>;

export async function extractTransactionsFromText(input: ExtractTransactionsInput): Promise<ExtractTransactionsOutput> {
  const prompt = ai.definePrompt({
    name: 'extractTransactionsPrompt',
    input: {
      schema: ExtractTransactionsInputSchema,
    },
    output: {
      schema: ExtractTransactionsOutputSchema,
    },
    prompt: `You are an expert at parsing financial text. Analyze the following text and extract all transaction details. Today's date is {{currentDate}}.

Your task is to extract transactions from the user's text. For each transaction, you must identify:
1.  **Merchant/Description**: The name of the merchant, or a category like "Groceries", "Transport". If no merchant or category is mentioned, use "Default".
2.  **Amount**: The numeric value of the transaction.
3.  **Date**: The date of the transaction. If no date is mentioned, use today's date ({{currentDate}}). The format must be YYYY-MM-DD.
4.  **Type**: Determine if it's a 'debit' (money spent, paid, bought) or 'credit' (money received, salary).

Example: "spent 450 on groceries" -> { merchant: "Groceries", amount: 450, date: "{{currentDate}}", type: "debit" }
Example: "paid 200 for transport" -> { merchant: "Transport", amount: 200, date: "{{currentDate}}", type: "debit" }
Example: "bought 300 snacks" -> { merchant: "Snacks", amount: 300, date: "{{currentDate}}", type: "debit" }

Even if the text is very simple, like "spent 500", do your best to fill in the details.
Example: "spent 500" -> { merchant: "Default", amount: 500, date: "{{currentDate}}", type: "debit" }

Text to analyze:
{{{text}}}

Return the data as a structured JSON object.
  `,
  });

  const extractTransactionsFlow = ai.defineFlow(
    {
      name: 'extractTransactionsFlow',
      inputSchema: ExtractTransactionsInputSchema,
      outputSchema: ExtractTransactionsOutputSchema,
    },
    async (input) => {
      const currentDate = new Date().toLocaleDateString('en-CA'); // YYYY-MM-DD format
      const { output } = await prompt({ ...input, currentDate });
      return output!;
    }
  );
  return extractTransactionsFlow(input);
}
