
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI-powered flow for extracting transaction details from raw text.
 * 
 * - extractTransactionsFromText - A function that parses text to identify and structure financial transactions.
 * - ExtractTransactionsInput - The input type for the extraction flow.
 * - ExtractTransactionsOutput - The output type for the extraction flow.
 * - Transaction - A structured representation of a single financial transaction.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const TransactionSchema = z.object({
  place: z.string().describe('The name of the place or a description of the expense, like "groceries" or "transport".'),
  amount: z.number().describe('The monetary value of the transaction.'),
  date: z.string().describe('The date of the transaction in YYYY-MM-DD format.'),
  type: z.enum(['debit', 'credit']).describe('The type of transaction (debit or credit).'),
});

export type Transaction = z.infer<typeof TransactionSchema>;

const ExtractTransactionsInputSchema = z.object({
  text: z.string().describe('A block of text, a single SMS, or multiple messages, potentially containing one or more transaction descriptions.'),
});

export type ExtractTransactionsInput = z.infer<typeof ExtractTransactionsInputSchema>;

const ExtractTransactionsOutputSchema = z.object({
  transactions: z.array(TransactionSchema).describe('An array of structured transaction objects found in the text.'),
});

export type ExtractTransactionsOutput = z.infer<typeof ExtractTransactionsOutputSchema>;

export async function extractTransactionsFromText(input: ExtractTransactionsInput): Promise<ExtractTransactionsOutput> {
  const prompt = ai.definePrompt({
    name: 'extractTransactionsPrompt',
    input: {
      schema: ExtractTransactionsInputSchema,
    },
    output: {
      schema: ExtractTransactionsOutputSchema,
    },
    prompt: `You are an expert at parsing financial text and SMS messages. Analyze the following text and extract all transaction details. Today's date is {{currentDate}}.

Your task is to extract transactions from the user's text. For each transaction, you must identify:
1.  **Place/Description**: The name of the place or service (e.g., 'Groceries', 'Amazon', 'Transport'). If no specific place or category is mentioned, use the most appropriate category from the context, or "Default" if none fits.
2.  **Amount**: The numeric value of the transaction. Look for currency symbols like '₹' or 'Rs.'.
3.  **Date**: The date of the transaction. If no date is mentioned, use today's date ({{currentDate}}). The format must be YYYY-MM-DD.
4.  **Type**: Determine if it's a 'debit' (money spent, paid, bought) or 'credit' (money received, salary).

Handle various formats and be flexible:
- "You spent ₹450 at Groceries" -> { place: "Groceries", amount: 450, date: "{{currentDate}}", type: "debit" }
- "Rs. 250 at XYZ" -> { place: "XYZ", amount: 250, date: "{{currentDate}}", type: "debit" }
- "₹600 from Amazon" -> { place: "Amazon", amount: 600, date: "{{currentDate}}", type: "debit" }
- "paid 200 for transport" -> { place: "Transport", amount: 200, date: "{{currentDate}}", type: "debit" }
- "bought 300 snacks" -> { place: "Snacks", amount: 300, date: "{{currentDate}}", type: "debit" }

If the text contains multiple transactions, extract all of them.
Example: "spent 450 on groceries paid 200 for transport bought 300 snacks" -> [{ place: "Groceries", amount: 450, date: "{{currentDate}}", type: "debit" }, { place: "Transport", amount: 200, date: "{{currentDate}}", type: "debit" }, { place: "Snacks", amount: 300, date: "{{currentDate}}", type: "debit" }]

If the text is very simple, like "spent 500", do your best to fill in the details.
Example: "spent 500" -> { place: "Default", amount: 500, date: "{{currentDate}}", type: "debit" }

Text to analyze:
{{{text}}}

Return the data as a structured JSON object.
  `,
  });

  const extractTransactionsFlow = ai.defineFlow(
    {
      name: 'extractTransactionsFlow',
      inputSchema: ExtractTransactionsInputSchema,
      outputSchema: ExtractTransactionsOutputSchema,
    },
    async (input) => {
      const currentDate = new Date().toLocaleDateString('en-CA'); // YYYY-MM-DD format
      const { output } = await prompt({ ...input, currentDate });
      return output!;
    }
  );
  return extractTransactionsFlow(input);
}
