// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI-powered flow for extracting transaction details from raw text.
 * 
 * - extractTransactionsFromText - A function that parses text to identify and structure financial transactions.
 * - ExtractTransactionsInput - The input type for the extraction flow.
 * - ExtractTransactionsOutput - The output type for the extraction flow.
 * - Transaction - A structured representation of a single financial transaction.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const TransactionSchema = z.object({
  merchant: z.string().describe('The name of the merchant or where the transaction occurred.'),
  amount: z.number().describe('The monetary value of the transaction.'),
  date: z.string().describe('The date of the transaction in YYYY-MM-DD format.'),
  type: z.enum(['debit', 'credit']).describe('The type of transaction (debit or credit).'),
});

export type Transaction = z.infer<typeof TransactionSchema>;

const ExtractTransactionsInputSchema = z.object({
  text: z.string().describe('A block of text, potentially containing one or more transaction descriptions, like from an SMS message.'),
});

export type ExtractTransactionsInput = z.infer<typeof ExtractTransactionsInputSchema>;

const ExtractTransactionsOutputSchema = z.object({
  transactions: z.array(TransactionSchema).describe('An array of structured transaction objects found in the text.'),
});

export type ExtractTransactionsOutput = z.infer<typeof ExtractTransactionsOutputSchema>;

export async function extractTransactionsFromText(input: ExtractTransactionsInput): Promise<ExtractTransactionsOutput> {
  const prompt = ai.definePrompt({
    name: 'extractTransactionsPrompt',
    input: {
      schema: ExtractTransactionsInputSchema,
    },
    output: {
      schema: ExtractTransactionsOutputSchema,
    },
    prompt: `You are an expert at parsing financial text messages. Analyze the following text and extract all transaction details. For each transaction, identify the merchant, amount, date, and whether it was a debit (money spent) or credit (money received). Today is {{currentDate}}.

  Text to analyze:
  {{{text}}}

  Return the data as a structured JSON object.
  `,
  });

  const extractTransactionsFlow = ai.defineFlow(
    {
      name: 'extractTransactionsFlow',
      inputSchema: ExtractTransactionsInputSchema,
      outputSchema: ExtractTransactionsOutputSchema,
    },
    async (input) => {
      const currentDate = new Date().toLocaleDateString('en-CA'); // YYYY-MM-DD format
      const { output } = await prompt({ ...input, currentDate });
      return output!;
    }
  );
  return extractTransactionsFlow(input);
}
