// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-driven insights on spending habits and potential savings opportunities.
 *
 * - getSpendingInsights - A function that provides AI-driven insights on spending habits and potential savings opportunities.
 * - SpendingInsightsInput - The input type for the getSpendingInsights function.
 * - SpendingInsightsOutput - The return type for the getSpendingInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SpendingInsightsInputSchema = z.object({
  income: z.number().describe('The user monthly income.'),
  expenses: z
    .array(z.object({
      category: z.string().describe('The category of the expense.'),
      amount: z.number().describe('The amount spent on the expense.'),
    }))
    .describe('A list of expenses with category and amount.'),
  savingsGoal: z.number().describe('The user savings goal.'),
});

export type SpendingInsightsInput = z.infer<typeof SpendingInsightsInputSchema>;

const SpendingInsightsOutputSchema = z.object({
  insights: z.string().describe('AI-driven insights on spending habits and potential savings opportunities.'),
});

export type SpendingInsightsOutput = z.infer<typeof SpendingInsightsOutputSchema>;

export async function getSpendingInsights(input: SpendingInsightsInput): Promise<SpendingInsightsOutput> {
  return spendingInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'spendingInsightsPrompt',
  input: {
    schema: SpendingInsightsInputSchema,
  },
  output: {
    schema: SpendingInsightsOutputSchema,
  },
  prompt: `You are a personal finance advisor. Analyze the user's spending habits and provide insights on potential savings opportunities.

  Income: {{income}}
  Expenses:
  {{#each expenses}}
  - Category: {{category}}, Amount: {{amount}}
  {{/each}}
  Savings Goal: {{savingsGoal}}

  Provide clear, actionable insights and recommendations.
  `,
});

const spendingInsightsFlow = ai.defineFlow(
  {
    name: 'spendingInsightsFlow',
    inputSchema: SpendingInsightsInputSchema,
    outputSchema: SpendingInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
